;$id: https://raw.githubusercontent.com/u-packs/HASchemas/main/schemas/websocket/base.yaml
$schema: http://json-schema.org/draft-07/schema#
description: https://developers.home-assistant.io/docs/api/websocket
type: object
title: Base Message
properties:
  type:
    $ref: https://raw.githubusercontent.com/u-packs/HASchemas/main/schemas/shared/type.yaml
  id:
    description: The ID of the response will point at the original ID of this message.
    type: integer
    minimum: 0
required:
  - type
  - id
additionalProperties: true
