$id: https://raw.githubusercontent.com/u-packs/HASchemas/main/schemas/rest/response/config.yaml
$schema: http://json-schema.org/draft-07/schema#
description: https://developers.home-assistant.io/docs/api/rest/
title: Config
type: object
additionalProperties: false
required:
  - components
  - config_dir
  - elevation
  - latitude
  - longitude
  - time_zone
  - unit_system
  - whitelist_external_dirs
  - version
  - allowlist_external_dirs
  - allowlist_external_urls
  - config_source
  - safe_mode
  - state
  - currency
properties:
  components:
    description: List of components that are included in the Home Assistant configuration.
    type: array
    additionalItems: false
    items:
      type: string
  config_dir:
    description: Directory that contain the HomeAssistant configuration files.
    type: string
  elevation:
    description: Elevation of the Home Assistant installation.
    type: number
  latitude:
    description: Latitude of the Home Assistant installation.
    type: number
  longitude:
    description: Longitude of the Home Assistant installation.
    type: number
  location_name:
    description: Name of the Home Assistant installation.
    type: string
  time_zone:
    description: Time zone of the Home Assistant installation.
    type: string
  unit_system:
    description: Unit system of the Home Assistant installation.
    type: object
    additionalProperties: false
    required:
      - length
      - mass
      - temperature
      - volume
      - accumulated_precipitation
      - wind_speed
      - pressure
    properties:
      length:
        description: Length unit of the Home Assistant installation.
        type: string
      accumulated_precipitation:
        description: Accumulated precipitation unit of the Home Assistant installation.
        type: string
      pressure:
        description: Pressure unit of the Home Assistant installation.
        type: string
      wind_speed:
        description: Wind speed unit of the Home Assistant installation.
        type: string
      mass:
        description: Mass unit of the Home Assistant installation.
        type: string
      temperature:
        description: Temperature unit of the Home Assistant installation.
        type: string
      volume:
        description: Volume unit of the Home Assistant installation.
        type: string
  version:
    description: Version of the Home Assistant installation.
    type: string
  whitelist_external_dirs:
    description: List of directories that are whitelisted for access from the Home Assistant installation.
    type: array
    additionalItems: false
    items:
      type: string
  allowlist_external_urls:
    description: List of URLs that are whitelisted for access from the Home Assistant installation.
    type: array
    additionalItems: false
    items:
      type: string
  allowlist_external_dirs:
    description: List of directories that are whitelisted for access from the Home Assistant installation.
    type: array
    additionalItems: false
    items:
      type: string
  config_source:
    description: Source of the Home Assistant configuration.
    type: string
  safe_mode:
    description: Safe mode of the Home Assistant installation.
    type: boolean
  state:
    description: State of the Home Assistant installation.
    type: string
  external_url:
    description: External URL of the Home Assistant installation.
    type:
      - string
      - "null"
  internal_url:
    description: Internal URL of the Home Assistant installation.
    type:
      - string
      - "null"
  currency:
    description: Currency of the Home Assistant installation.
    type: string
  country:
    description: Language of the Home Assistant installation.
    type:
      - string
      - "null"
  language:
    default: "en"
    description: Language of the Home Assistant installation.
    type:
      - string
      - "null"
